version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    command: [sh, -c, npm install && node index.js]
    environment:
      - GIT=https://github.com/akakou-stash/sheld-test-repo
      - SSL_PORT=443
      - PLAIN_PORT=80
      - WEB_PORT=8443
      - SSL_KEY=/keys/key.pem
      - SSL_CERT=/keys/server.crt
    links:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./db/data:/data/db
    ports:
      - "27017:27017"
    environment:
      - IMPORT_FROM_VOLUME=true
