version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: [sh, -c, npm install && node index.js]
    environment:
      - GIT=https://github.com/akakou-stash/sheld-test-repo
      - PORT=443
      - SSL_KEY=/keys/key.pem
      - SSL_CERT=/keys/server.crt
    links:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./db/data:/data/db
      - ./db/init/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    environment:
      - IMPORT_FROM_VOLUME=true
      - MONGO_INITDB_DATABASE=fluentd
